### ISSUE TITLE
Dev plan

### ISSUE THREAD

**Issue by ericphanson** [JuliaOpt/Convex.jl#320]
I'm planning on making some changes and improvements, and I thought I'd write out my plan, in case there are objections and just so these changes aren't coming out of nowhere. It's hard to say how much of this I'll actually get done, but I've consistently been feeling pretty motivated on weekends to work on this, so hopefully it's not too wildly ambitious.

*Ordered priorities:*

- [ ] Add some benchmarking. This is the first priority, because I want to make sure subsequent changes don't hurt performance. I'll probably put up a PR today or tomorrow and merge it fairly quickly, so that subsequent PRs can get benchmarked against master. This won't involve code changes to the Convex.jl `src` folder so there should be little chance of breaking anything.
- [ ] Get rid of global dictionary of variables (`id_to_variables`).  This is half the cause of #83, and I think there's a relatively easy fix. The hard bit is to make sure to not hurt perf too much, since we will have to do the work locally in the problem instead of once at variable construction time, so benchmarking is key.
- [ ] Get rid of the other global variable? I haven't looked into this, but it's used for dual values so it might be nice to do this before the next point. This would then close #83.
- [ ] Switch to MOI. This is maybe 80% done in my branch https://github.com/ericphanson/Convex.jl. I still need to populate dual variables, decide what to do with the various `can_solve_sdp` type methods, and clean up the code a bit (either get rid of MBP or make Convex usable with either MBP or MOI). Benchmarking is important here too, to make sure we haven't hurt model formulation speed with the new internals generating MOI functions and constraints. Ideally, we might get improvements.

*Optional:* 
- [ ] Add `AbstractTrees` dependency + methods, so a Convex.jl problem can be seen as an `AbstractTree` (?). I thought I might need this for (2), but I think I won't now, so it's kind of optional. It's nice because you can use `AbstractTrees.print_tree(p::Problem)` to generate a nice representation of the problem. This might actually give a nicer way to show the problem in the REPL which we could use for `show`. You can also use GraphPlots master and do `plot(TreePlot(p))` where `p::Problem` and get a visual representation of the problem (which was my motivation for https://github.com/JuliaPlots/GraphRecipes.jl/pull/80). The only downside is the dependency, which is 700 lines of Julia with no dependencies itself, which doesn't seem too bad. I might PR this one soon because it's already done locally.
- [ ] Finish + merge https://github.com/JuliaOpt/Convex.jl/pull/313. This PR touches almost every use of `Variable` (if only trivially replacing it by `AbstractVariable`) so it will need rebasing with each of the above changes. But it's really an enhancement / feature, not blocking for MOI, which is probably more important. It shouldn't have any perf consequences, but benchmarking would be nice to confirm. I see this as opening the door to DSLs based on top of Convex, and it may be better to wait for some of the big internals changes (e.g. switch to MOI) first, so that there's a stable base for those DSLs.
- [ ] #310: allows implementing more atoms, and make it easier to write DSLs on top of Convex. Might be able to remove some current atoms too (without feature loss). 
- [ ] #318: seems important for making `fix!` and `free!` have meaningful perf advantages for model formulation.
- [ ] Various doc changes and small fixes. E.g. I have some open PRs that I should rebase and double-check.

*Speculative*:
- [ ] Change how `conic_form!` works to be closer to MOI. Theoretically, each `conic_form!` could be directly generating MOI functions and constraints, instead of using `ConicObj`'s. This would give nicely typed objects which would hopefully address performance issues like https://github.com/JuliaOpt/Convex.jl/issues/254, and maybe others (which I haven't looked into too much). The end-state of this would be Convex being a front-end to MOI like JuMP, but with different syntax, DCP checking, and some pseudo-bridges on top. I think that's a reasonable place to be, and positions Convex well to take advantage of MOI's fast + high quality development. This would likely involve rewriting `conic_form!` for every atom.

**Comment by matbesancon** [comment]
I'm ok with at least the high-priority you defined above

**Comment by ericphanson** [comment]
For those following this plan: there’s a brief detour to https://github.com/JuliaOpt/Convex.jl/pull/328, which came about partly trying to get the tests working for MPB and MOI simultaneously, with the plan of supporting both— at least until it’s inconvenient; since Convex has a few points of contact with the middle layer, at this point it’s not really a problem to support both because the MPB code is already written. If we get to my speculative point above, I’d probably drop MPB.

**Comment by ericphanson** [comment]
We can’t super easily support both MPB and MOI simultaneously because they each represent SDP constraints in a different way, and we’d need a different conic_form! for each. We could propagate down the tree the information of whether or not we’re using an MOI solver. But I’m not sure that’s worth it, since it’s adding complexity to support superseded code.

**Comment by ericphanson** [comment]
I think updating the examples (and #335) will be my next priority now that #330 is essentially done

**Comment by ericphanson** [comment]
Next up is https://github.com/JuliaOpt/Convex.jl/pull/313 and https://github.com/JuliaOpt/Convex.jl/issues/346 to try to get an MOI release out soon.

**Comment by ericphanson** [comment]
See https://github.com/JuliaOpt/Convex.jl/issues/361 for new thoughts on v0.13.

**Comment by ericphanson** [comment]
0.13 is out!

The next steps that I see are #346 and #358 to setup a coherent public API, with deprecations, then a 1.0 release with that API. Then a non-breaking internals revamp for performance and ideally #310.

I’m not sure when all that will happen though though, possibly not for months, so if someone else has a different plan they want to pursue sooner, that seems fine as well :).

**Comment by ericphanson** [comment]
A bit of an update:

* I cleaned up and merged #358. Check it out!
* I have not worked on the public API (ref #346). It's hard and not super fun! It's also not completely clear if it's the right time for commit to a public API.
* I started working a bit on the "speculative" item "Change how conic_form! works to be closer to MOI". There is a proof of concept here https://github.com/jump-dev/Convex.jl/blob/180f639559df3d0b08b445274bce68d141cd518d/src/ConicFormProblem.jl which can solve one test problem (https://github.com/jump-dev/Convex.jl/issues/390), and matches JuMP performance (beating Convex.jl's current performance by a lot). I think this may be the right way forward for Convex.jl's internals, and can help with e.g. #388. To get better type stability, we may want to make some syntax changes like stopping supporting `x >= 0` where `x` is a vector or matrix. This definitely needs a lot more thought though.

One other note: as I mentioned in my JuliaCon talk (https://www.youtube.com/watch?v=iczcGK6G_sE), I may not be working on Convex.jl as often from now on. (But this MOI updating thing has gotten me excited again...)
